name:                TesterProject
version:             0.1.0.0
github:              "githubuser/TesterProject"
license:             BSD3
author:              "Luan Williams"
maintainer:          "willialu@tcd.ie"
copyright:           "Luan Williams"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TesterProject#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  TesterProject-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TesterProject
    - DAG

tests:
  TesterProject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TesterProject
    - hspec
    - QuickCheck
